name: Develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'refactor/**'
      - master

env:
  node-version: 16.x
  stage: develop
  domain: pet-backend.railway.internal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Show Current Directory
        run: pwd

      - name: List Directory Contents
        run: ls -la

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Show Current Directory in Deploy
        run: pwd

      - name: List Directory Contents in Deploy
        run: ls -la

      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --yes --env ${{ env.stage }}

  deploy-main-successful:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Application updated: **${{ env.stage }}**. The **server** at https://${{ env.domain }}/ has been updated.'
