name: Develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'refactor/**'

env:
  node-version: 16.x
  stage: develop
  domain: pet-backend.railway.internal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Install Railway
         run: npm i -g @railway/cli

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: bervProject/railway-deploy@main
        with:
          service: pet-backend
          railway_token: ${{ secrets.RAILWAY_TOKEN }}        

  deploy-main-succefull:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Enviando notificação Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Aplicação atualizada: **${{ env.stage }}**. O **servidor** do ambiente https://${{ env.domain }}/ foi atualizado.'
      - name: Enviando mensagem no Discord
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/${{ secrets.WEBHOOK_ID }}/${{ secrets.WEBHOOK_TOKEN }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Aplicação atualizada: **${{ env.stage }}**. O **servidor** do ambiente https://${{ env.domain }}/ foi  atualizado.'


